version: '3.5'

services:
  postgres:
    container_name: postgres-api
    image: postgres
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - .:/data/postgres
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'

  api:
    build: .
    command: npm run start:dev
    volumes:
      - .:/usr/app/api/
      - /usr/app/api/node_modules
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_PORT: '${POSTGRES_PORT}'
      POSTGRES_HOST: postgres-api
