version: '3.5'

services:
  postgres:
    container_name: postgres-api
    image: postgres
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - .:/data/postgres
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
